### ISSUE TITLE
Poprawki w sprzęcie

### ISSUE THREAD

**Issue by JakubRakus** [rafalo235/nixie-clock-hw#1]
Schemat główny:
 - linie SDA i SCL - dodać podciąganie rezystorami 4k7 do +5V, sprawdzić czy port w STM32 jest 5V-tolerant;
- dodać kondensator 100u przy złączu ESP8266;
- dodać kondensatory na zasilaniu procesora zgodnie z jego notą katalogową (kondensator przy KAŻDYM pinie VDD);
- zasilanie VDDA procesora przez układ LC (jeśli będzie wykorzystany wewnętrzny ADC);
- jeśli będzie wykorzystany enkoder do ustawiania godziny należy się też zastanowić nad użyciem go również do ustawiania jasności zamiast potencjometru RV1. 

Zasilacz:
- zmienić wartości kondensatorów na wartości z typoszeregu (np. 470u zamiast 400u);
- dioda D2 - nie jest potrzebna;
- dioda D4 - powinna być dioda ultraszybka np. UF4004;
- bramka Q1 powinna mieć rezystor do masy 1k;
- zamiast stabilizatora U3 lepsza będzie przetwornica DC/DC 12V/5V;
- zasilanie +3.3V - zastosować LDO z prądem znamionowym 1A (ze względu na duży impulsowy prąd pobierany przez ESP);
- brakuje bezpiecznika po stronie 230VAC;
- zamiast C4 powinny być dwa kondensatory do ochronnego.

NIXIE connector:
- dodać 100n na zasilaniu PCF8574;
- na złącza P3, P4 doprowadzone jest +5V, ale nie jest wykorzystane na płytkach z lampami.

**Comment by rafalo235** [comment]
Chyba chodzi o kondensatory 100n? Tak jest według noty katalogowej CD00161566.pdf - strona 36
[CD00161566.pdf](https://github.com/rafalo235/nixie-clock-hw/files/576602/CD00161566.pdf)

**Comment by JakubRakus** [comment]
- tak, ale teraz jest trochę przekombinowane (rozwiązanie z noty katalogowej jest "na wyrost") - wystarczy 100n MLCC do każdego pinu zasilającego VDD, a do VDDA dławik 1uH + 100n MLCC. Na cały procek wystarczy 10u tantalowy zamiast tych dwóch 4u7 + 1u - ogólnie filtrowanie zasilania procesora trzeba trochę inaczej narysować, teraz jest mało czytelny schemat;
- 100u do ESP też tantalowy;
- do pinów VSS procesora podłączone jest VDD, a powinno być GND.

**Comment by rafalo235** [comment]
Poprawki gotowe - nie znalazłem noty aplikacyjnej do układu ROM-1205S, więc użycie C14 i L3 zależy od Ciebie. Do sprawdzenia jest też zastosowanie AMS1117. Znalazłem w internecie takie zastosowanie, ale obawiam się czy prąd upływu przez dzielnik napięcia R9/R8 nie będzie za duży.

**Comment by JakubRakus** [comment]
Zasilacz:
- otoczenie AMS1117 - ok, tylko C17 dać większy, np. 100u.
- filtr od strony 230 VAC - kondensatory C12 i C13 muszą być 680n (600n nikt nie produkuje), [MKP X1/Y2 na 275 VAC](http://www.tme.eu/pl/katalog/elementy-pasywne_112309/#id_category=112352&s_field=artykul&s_order=ASC&visible_params=2%2C10%2C31%2C32%2C39%2C42%2C45%2C45%2C115%2C118%2C118%2C124%2C2650&used_params=45%3A25298%3B118%3A24916%3B)
- na wyjściu AME40-12 dodać dwa kondensatory tantalowe 470u/16V, z tego dziwnego filtru C14 i L3 zostawić tylko kondensator 100n
- na wyjściu ROM1205 dodać filtr LC jak w [tej nocie](http://www.farnell.com/datasheets/1647587.pdf) - strona 4
- dzielnik R10/R11 przy takich wartościach elementów daje podział (R11+R10)/R11 = 101 - można tak zostawić, ale trzeba o tym pamiętać przy pisaniu programu, dobrze by było żeby te rezystory były o tolerancji 1%

Mainboard:
- C9 zmienić na 100n
- usunąć C11 przy enkoderze - drgania styku trzeba eliminować w programie albo zrobić znacznie bardziej rozbudowany układ, dokładanie TYLKO kondensatora w tym miejscu może pogorszyć sprawę zamiast polepszyć, [poczytaj tu](http://www.eng.utah.edu/~cs5780/debouncing.pdf)
- uwaga co do sygnałów 200VSENSE i BRIGHTPWM: 200VSENSE jest teraz na pinie obok linii enkodera - kręcenie enkoderem może wprowadzać zakłócenia do pomiaru, natomiast sygnał PWM z BRIGHTPWM będzie zakłócać komunikację na liniach UART do ESP - trzeba 200VSENSE i BRIGHTPWM przełożyć na jakieś inne piny
- piny w STM32 są 5V-tolerant, ale można by się jednak zastanowić nad dodaniem na linie SDA i SCL prostego [konwertera napięć](http://headfuzz.co.uk/files/robotics/i2c/i2ctranslator-sch.png)
